### ISSUE TITLE
...Actually believe you meant to install standard and not standardjs

### ISSUE THREAD

**Issue by jimmywarting** [kleros/gtcr-subgraph#1]
https://github.com/kleros/gtcr-subgraph/blob/c2276976739ea581153390a81f95d194278082f3/package.json#L59

**Comment by mtsalenc** [comment]
You are correct. But actually we shouldn't even be using standard in this repo.

Thanks for reporting.

**Comment by jimmywarting** [comment]
👍 just wanted to give u a heads up for bad similar package name, gl on your project
weather or not u use standard or not don't mathers to me 😉
