### ISSUE TITLE
Deployment to Arbitrum Rinkeby

### ISSUE THREAD

**Issue by jaybuidl** [kleros/gtcr-subgraph#16]

**Comment by greenlucid** [comment]
We will need to self-host an indexer for this, or abandon the idea. @geaxed

**Comment by jaybuidl** [comment]
@greenlucid was able to deploy it: https://thegraph.com/hosted-service/subgraph/greenlucid/curate-arbitrum-rinkeby

The graph is now saying [it was an outage](https://status.thegraph.com/incidents/p86hvhgzqwg1).
